language: node_js
sudo: false
node_js:
- '4.4'
before_install:
- npm install -g grunt-cli
notifications:
  email:
  - freedom@cs.washington.edu
env:
  global:
    - secure: "lt/+pqrnB/VOhlbU5QT8cqimnrRRJkYKlGsESB+Z2JYYm0yCTrYKxxY2Cp+YS/aj2bTsNz3htE0A94jTCKBfEXWiPiwRFX+rEqqxgG6bxKXhlq9e4pzoK12KCTxgR2ft8nCDTSBIxlAOGdRK2m3t67oYiEAJ0nJbxtDcVGDUsN0="
cache:
  directories:
  - node_modules
